version: "3.8"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: minmod-dashboard
    ports:
      - "8050:8050"
    environment: 
      - API_ENDPOINT=${API_ENDPOINT}
      - SPARQL_ENDPOINT=${SPARQL_ENDPOINT}
    command: "poetry run python app.py"

